/* GENERATED by gen/gen_art.py -- do not edit by hand. */
#pragma once

#include <lvgl.h>

#define BONGO_READY_W 28
#define BONGO_READY_H 56
#define BONGO_WAITING_W 28
#define BONGO_WAITING_H 56
#define BONGO_TAP0_W 28
#define BONGO_TAP0_H 56
#define BONGO_TAP1_W 28
#define BONGO_TAP1_H 56
#define BT_ON_W 14
#define BT_ON_H 18
#define BT_OFF_W 14
#define BT_OFF_H 18

LV_IMG_DECLARE(bongo_ready);
LV_IMG_DECLARE(bongo_waiting);
LV_IMG_DECLARE(bongo_tap0);
LV_IMG_DECLARE(bongo_tap1);
LV_IMG_DECLARE(bt_on);
LV_IMG_DECLARE(bt_off);
